columns: [
{data: 'check', name: 'check', orderable: false, searchable: false},
{data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
{data: 'student_image', name: 'student_image'},
{data: 'application_date', name: 'application_date'},
{data: 'student_name', name: 'student_name'},
{data: 'student_number', name: 'student_number'},
{data: 'student_type', name: 'student_type'},
{data: 'registration_name', name: 'registration_name'},
{data: 'division_grade', name: 'division_grade'},
{data: 'more_btn', name: 'more_btn', orderable: false, searchable: false},
],
